
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

const WBS_PATH = path.join(process.cwd(), 'docs', 'architecture', 'current_wbs.md');

async function auditWBS() {
    console.log("🦉 [Chief of Staff] Commencing Reverse-Engineering of WBS...");

    // 1. Identify Core Modules (Heuristic based on directory structure and files)
    const srcDir = path.join(process.cwd(), 'src');
    const scriptsDir = path.join(process.cwd(), 'scripts');

    const hierarchy: any = {
        name: "Sovereign SDLC Platform v3.0",
        children: [
            {
                name: "Operational Sovereignty (Phase 10)",
                tasks: ["SRE Monitor (scripts/sre_monitor.ts)", "Auto-Revert Logic (scripts/ops/revert_change.ts)"]
            },
            {
                name: "Executive Hierarchy (Phase 11)",
                tasks: ["Governance Agent (scripts/governance/check_constitution.ts)", "Signature Protocol (scripts/governance/sign_off.ts)"]
            },
            {
                name: "Value Alignment (Phase 12)",
                tasks: ["Digital Atrophy Analysis (scripts/value/analyze_atrophy.ts)"]
            },
            {
                name: "Spec-Driven Delivery (Phase 13)",
                tasks: ["Specify/Plan/Taskify Pipeline (scripts/sdd/*)"]
            }
        ]
    };

    // 2. Generate Markdown WBS
    let wbsMd = `# Work Breakdown Structure (WBS) - Post-Facto Audit\n\n`;
    wbsMd += `> [!NOTE]\n> Generated by the Chief of Staff Agent. This serves as the 'Scope Baseline'.\n\n`;

    hierarchy.children.forEach((branch: any) => {
        wbsMd += `## 📦 ${branch.name}\n`;
        branch.tasks.forEach((task: string) => {
            wbsMd += `- [x] ${task}\n`;
        });
        wbsMd += `\n`;
    });

    wbsMd += `## 🕒 Critical Path Assessment\n`;
    wbsMd += `1. **Architecture Core** -> **Monitoring Layer** -> **Active Defense** -> **Executive Command**\n`;

    if (!fs.existsSync(path.dirname(WBS_PATH))) {
        fs.mkdirSync(path.dirname(WBS_PATH), { recursive: true });
    }

    fs.writeFileSync(WBS_PATH, wbsMd);

    console.log(`\n✅ [Chief of Staff] WBS Audit Complete. Scope Baseline established at: ${WBS_PATH}`);
}

auditWBS();
